### ISSUE TITLE
Add metrics for successful/failed context creation

### ISSUE THREAD

**Issue by tlnd** [travelping/ergw#100]
Explicit metrics for successfully created contexts/sessions as well as failed/rejected context/session creations is required -- this is an important metric for operation and cannot be reasonably deduced from the existing metrics.

These metrics should cover both situations where contexts are initiated by a peer sending requests, as well as if ergw sending requests towards a peer.

"Failed" creations could mean that the request was rejected for some reason (by ergw or peer) or no response was received for a context/session create request.

I think it makes sense to add those as per-peer metric.  Ideally, the reject/fail cause is part of the metric.

**Comment by ebengt** [comment]
Done in ergw cf9569f5f68dbeeaf8315e8483bc456ec9fd2a23
