### ISSUE TITLE
VRF Routing not working

### ISSUE THREAD

**Issue by msupra** [travelping/ergw#11]
Hi

When testing from sgsn simulator, I try to ping different endpoints after establishing PDP context. I am able to ping the host on which the ergw runs (10.0.0.151, ens3). I am able to ping upstream vrf (10.0.0.155 ens8).

I am not able to ping the default gateway or anything beyond. My config below. My instinct says that the routing is not correctly instantiated:

vrf-lite: iproute2 version iproute2-ss161212
#!/bin/sh

ifup() {
    /sbin/ip link add $1 type vrf table $2
    /sbin/ip link set dev $1 up
    /sbin/ip rule add oif $1 table $2
    /sbin/ip rule add iif $1 table $2

    /sbin/ip link set dev $3 master $1
    /sbin/ip link set dev $3 up
    /sbin/ip addr flush dev $3
    /sbin/ip addr add $4 dev $3
    /sbin/ip route add table $2 default via $5
}

ifup upstream 10 ens8 10.0.0.155/24 10.0.0.1
ifup grx 20 ens9 10.0.0.154/24 10.0.0.1

exit 0

ergw:
         {vrfs,
          [{upstream, [{pools,  [{{10, 0, 0, 1}, {10, 0, 0, 254}, 24},
                                 {{16#8001, 0, 0, 0, 0, 0, 0, 0}, {16#8001, 0, 0, 16#FFFF, 0, 0, 0, 0}, 64}
                                ]},
                       {'MS-Primary-DNS-Server', {8,8,8,8}},
                       {'MS-Secondary-DNS-Server', {8,8,4,4}},
                       {'MS-Primary-NBNS-Server', {127,0,0,1}},
                       {'MS-Secondary-NBNS-Server', {127,0,0,1}}
                      ]}
          ]},

gtp_u_kmod:
{gtp_u_kmod, [
               {sockets, [{grx, [{ip, {10,0,0,154}},
                                 {netdev, "grx"},
                                 {vrf, [{routes, [{{10, 0, 0, 0}, 24}]},
                                        {netdev, "upstream"}
                                       ]}
                                ]}
                         ]}
              ]},

After starting all processes the route command shows:
root@ggsn:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    0      0        0 ens3
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 ens3

**Comment by RoadRunnr** [comment]
your configuration can not work this way.

It is not possible to use the same IP range on the GTP interface and the routing interface.

**Comment by msupra** [comment]
Hi

Is it at all possible that you can give me a working config for the vrf, GTP and routing interface, that I can use to configure my environment. I am really struggling to configure a test system where I can create a PDP context and then ping anything further than ens8 (upstream) IP. This is my current config which does not work:

#!/bin/sh

ifup() {
    /sbin/ip link add $1 type vrf table $2
    echo "$2 $1" > /etc/iproute2/rt_tables.d/$1.conf
    /sbin/ip link set dev $1 up
    /sbin/ip rule add oif $1 table $2
    /sbin/ip rule add iif $1 table $2

    /sbin/ip link set dev $3 master $1
    /sbin/ip link set dev $3 up
    /sbin/ip addr flush dev $3
    /sbin/ip addr add $4 dev $3
    /sbin/ip route add table $2 default via $5
}

ifup upstream 10 ens8 172.0.0.1/30 172.0.0.3
ifup grx 20 ens9 10.0.0.154/24 10.0.0.1

exit 0

{ergw, [{sockets,
          [{irx, [{type, 'gtp-c'},
                  {ip,  {10,0,0,154}},
                  {netdev, "grx"},
                  freebind
                 ]},
           {grx, [{type, 'gtp-u'},
                  {node, 'gtp_u_kmod@ggsn'},
                  {name, 'grx'}]}
          ]},

         {vrfs,
          [{upstream, [{pools,  [{{172, 0, 0, 1}, {172, 0, 0, 254}, 24},
                                 {{16#8001, 0, 0, 0, 0, 0, 0, 0}, {16#8001, 0, 0, 16#FFFF, 0, 0, 0, 0}, 64}
                                ]},
                       {'MS-Primary-DNS-Server', {8,8,8,8}},
                       {'MS-Secondary-DNS-Server', {8,8,4,4}},
                       {'MS-Primary-NBNS-Server', {127,0,0,1}},
                       {'MS-Secondary-NBNS-Server', {127,0,0,1}}
                      ]}
          ]},

{gtp_u_kmod, [
               {sockets, [{grx, [{ip, {10,0,0,154}},
                                 {netdev, "grx"},
                                 {vrf, [{routes, [{{172, 0, 0, 0}, 24}]},
                                        {netdev, "upstream"}
                                       ]}
                                ]}
                         ]}
              ]},

Regards
Morne
