### ISSUE TITLE
Unable to allocate IP pools

### ISSUE THREAD

**Issue by Twig96** [travelping/ergw#196]
Hi, 

I'm testing the deployment of ergw PGW + vpp UPF with the addition of a sgsnemu node. The nodes run without errors but the 'Create PDP context request' initiated by the SGSN receives negative response from the PGW with code 199 (No resources available) after the 'Sx Association Setup' and 'Sx session establishment'.

Appearently, inspecting the sniffed packets, the PGW is unable to allocate IP addresses for the end users although I defined the IP pools in the ergw.config file for building the release.

I'm wondering what am I doing wrong, down here I attach the configuration file for ergw: 

 %-*-Erlang-*-

 [{setup, [{data_dir, "/var/lib/ergw"},
	  {log_dir,  "/var/log/ergw-c-node"}
	 ]},

 {kernel,
  [{logger,
    [{handler, default, logger_std_h,
      #{level => info,
	config =>
	    #{sync_mode_qlen => 10000,
	      drop_mode_qlen => 10000,
	      flush_qlen     => 10000}
       }
     }
    ]}
  ]},

 {ergw, 

        [{'$setup_vars',
	  [{"ORIGIN", {value, "epc.mnc001.mcc001.3gppnetwork.org"}}]},
	 {http_api,
	  [{port, 8080},
	   {ip, {0,0,0,0}}
	  ]},
	 {sockets,
	  [{'cp-socket',
	    [{type, 'gtp-u'},
	     {vrf, cp},
	     {ip, {172,20,21,1}},
	     {netdev, "sxb-cp"},
	     {reuseaddr, true}
	    ]},
	   {irx, [{type, 'gtp-c'},
		  {vrf, epc},
		  {ip, {172,20,20,1}},
		  {netdev, "grx-cp"},
		  {reuseaddr, true}
		 ]}
	  ]},

	 {vrfs,
	  [{sgi, [{pools,  [{{10, 80, 0, 1}, {10, 80, 255, 254}, 32},
			    {{16#8001, 0, 0, 0, 0, 0, 0, 0},
			     {16#8001, 0, 0, 16#FFFF, 0, 0, 0, 0}, 64}
			   ]},
		  {'MS-Primary-DNS-Server', {8,8,8,8}},
		  {'MS-Secondary-DNS-Server', {8,8,4,4}},
		  {'MS-Primary-NBNS-Server', {127,0,0,1}},
		  {'MS-Secondary-NBNS-Server', {127,0,0,1}}
		 ]}
	  ]},

	 {sx_socket,
	  [{node, 'ergw'},
	   {name, 'ergw'},
	   {socket, 'cp-socket'},
	   {ip, {172,20,21,1}},
	   {netdev, "sxb-cp"}
	  ]},

	 {handlers,
	  [{'h1', [{handler, pgw_s5s8},
		   {protocol, gn},
		   {sockets, [irx]},
		   {node_selection, [default]}
		  ]},
	   {'h2', [{handler, pgw_s5s8},
		   {protocol, s5s8},
		   {sockets, [irx]},
		   {node_selection, [default]}
		  ]}
	  ]},

	 {apns,
	  [{[<<"tpip">>, <<"net">>], [{vrf, sgi}]},
	   {[<<"APN1">>], [{vrf, sgi}]}
	  ]},

	 {node_selection,
	  [{default,
	    {static,
	     [
	      %% APN NAPTR alternative
	      {"_default.apn.$ORIGIN", {300,64536},
	       [{"x-3gpp-upf","x-sxb"}],
	       "topon.sx.prox01.$ORIGIN"},

	      {"web.apn.$ORIGIN", {300,64536},
	       [{"x-3gpp-upf","x-sxb"}],
	       "topon.sx.prox01.$ORIGIN"},

	      %% A/AAAA record alternatives
	      {"topon.sx.prox01.$ORIGIN", [{172,20,21,2}], []}
	     ]
	    }
	   }
	  ]
	 },

	 {nodes,
	  [{default,
	    [{vrfs,
	      [{cp, [{features, ['CP-Function']}]},
	       {epc, [{features, ['Access']}]},
	       {sgi, [{features, ['SGi-LAN']}]}]
	     }]
	   }]
	 }
	]},

 {ergw_aaa,
  [{transports, []},
   {handlers,
    [{ergw_aaa_static,
	[{'NAS-Identifier',          <<"NAS-Identifier">>},
	 {'Framed-Protocol',         'PPP'},
	 {'Service-Type',            'Framed-User'},
	 {'Node-Id',                 <<"PGW-001">>},
	 {'Charging-Rule-Base-Name', <<"m2m0001">>},
	 {rules, #{'Default' =>
		       #{'Rating-Group' => [3000],
			 'Flow-Information' =>
			     [#{'Flow-Description' => [<<"permit out ip from any to assigned">>],
				'Flow-Direction'   => [1]    %% DownLink
			       },
			      #{'Flow-Description' => [<<"permit out ip from any to assigned">>],
				'Flow-Direction'   => [2]    %% UpLink
			       }],
			 'Metering-Method'  => [1],
			 'Precedence' => [100]
			}
		  }
	 }
	]}
    ]},

   {services,
    [{'Default', [{handler, 'ergw_aaa_static'}]}]},

   {apps,
    [{default,
      [{session, ['Default']},
       {procedures, [{authenticate, []},
		     {authorize, []},
		     {start, []},
		     {interim, []},
		     {stop, []}
		    ]}
      ]}
    ]}
  ]},

 {hackney, [
	    {mod_metrics, exometer}
	    ]},

 {jobs, [{samplers,
	  [{cpu_feedback, jobs_sampler_cpu, []}
	  ]},
	 {queues,
	  [{path_restart,
	    [{regulators, [{counter, [{limit, 100}]}]},
	     {modifiers,  [{cpu_feedback, 10}]} %% 10 = % increment by which to modify the limit
	    ]},
	   {create,
	    [{max_time, 5000}, %% max 5 seconds
	     {regulators, [{rate, [{limit, 100}]}]},
	     {modifiers,  [{cpu_feedback, 10}]} %% 10 = % increment by which to modify the limit
	    ]},
	   {delete,
	    [{regulators, [{counter, [{limit, 100}]}]},
	     {modifiers,  [{cpu_feedback, 10}]} %% 10 = % increment by which to modify the limit
	    ]},
	   {other,
	    [{max_time, 10000}, %% max 10 seconds
	     {regulators, [{rate, [{limit, 1000}]}]},
	     {modifiers,  [{cpu_feedback, 10}]} %% 10 = % increment by which to modify the limit
	    ]}
	  ]}
	]}
].

**Comment by RoadRunnr** [comment]
Your config is for an older version of ergw. The IP pool config has changed in 2.4.x. Have a look at the configs in the test suite for a working example, e.g. https://github.com/travelping/ergw/blob/master/test/pgw_SUITE.erl#L47-L204

**Comment by Twig96** [comment]
Thanks for the feedback, I managed to update the configuration file but now it displays a different error for which I will open another issue.
