### ISSUE TITLE
Feature: Configurable retry timings for SMF / UPF heartbeats

### ISSUE THREAD

**Issue by mgumz** [travelping/ergw#281]
Between SMF and UPF continuous heartbeat requests are sent to detect availability of the associated UPFs. If these heartbeat requests are not replied in a given time frame, the UPF is considered to be unavailable and thus all the sessions are released.

The timeout value at the moment is hardcoded and rather strict:

https://github.com/travelping/ergw/blob/09e97cb0b0e69d6536daef02b599c4492e7b3fc5/src/ergw_sx_node.erl#L643-L647

5s for the first timeout
0.5 time out for retries
5 retries

Which makes it like 7.5s to deduce the UPF is not reachable.

For some deployment scenarios that is a really tight deadline to meet.

With a configurable values the situation could be adjusted to the concrete deployment scenario.

**Comment by vkatsuba** [comment]
Closed. Implemented in release [2.8.3](https://github.com/travelping/ergw/releases/tag/2.8.3).
