### ISSUE TITLE
CT; proxy_lib_SUITE is broken

### ISSUE THREAD

**Issue by RoadRunnr** [travelping/ergw#336]
commit 1f1b2217a81e0d8b4edbbbca8cf6fe394f79e03f broken the suite.

It does pass when run as part of a full run, but running it standalone with `rebar3 ct --suite=proxy_lib_SUITE` fails because the gtp_path_reg is not started.

**Comment by vkatsuba** [comment]
Cannot reproduce:
```sh
$ ./rebar3 ct --suite=proxy_lib_SUITE
===> Analyzing applications...
===> Compiling ergw
===> Running Common Test suites...
%%% proxy_lib_SUITE: .
All 1 tests passed.
```
Also looks like https://github.com/travelping/ergw/blob/master/test/proxy_lib_SUITE.erl#L112 the `gtp_path_reg` is started and `gtp_path_reg:start_link()` have output like `{ok,<0.927.0>}`.
