### ISSUE TITLE
DPDK Support 

### ISSUE THREAD

**Issue by eshikafe** [travelping/ergw#36]
Has anyone considered using dpdk as a data path provider or VPP, or OVS?

**Comment by hwinkel** [comment]
Yes, we have considered that already and collaboration is welcome. our first finding:

* VPP is fine for data path but also already incldes a full control plane so you double the work in erGW and there
* OvS is "just" a DPDK enabled switch which might stear traffic to the EPC VNF bu should not be the implementation IMHO
