### ISSUE TITLE
General Query , a novice one..Is this repo activaly manged , is it safe to consider for use ???

### ISSUE THREAD

**Issue by prasenjitpdas** [travelping/ergw#463]
General Query , a novice one..Is this repo activaly manged , is it safe to consider for use

**Comment by mgumz** [comment]
`ergw` is the base for our commercial products which runs multiple millions subscribers on every given day.

**Comment by prasenjitpdas** [comment]
Great and many many thanks @mgumz .  assured to see a team has my back. also looking fwd for contributing to this.

**Comment by RoadRunnr** [comment]
@prasenjitpdas active development of the commercial product has moved to an internal repository. The public version is currently not receiving update or fixes.

**Comment by prasenjitpdas** [comment]
thanks @RoadRunnr , this is the top point to consider . thanks for your input.
